name: File Change Trigger Workflow

on:
  push:
    paths:
      - source.xlsx

jobs:
  update_files:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Update
        run: |
          curl -X POST \
          -H "Content-Type: application/json" \
          -d '{"sourceFileId": "3ACD0680-3BC0-4D66-A492-AAAA1669846D", "destinationFileId": "51F9826C-7B53-4A60-A2F7-D05AC47E1618"}' \
          https://your-repl-url.repl.co/update_ppt
