name: Daily Update

on:
  schedule:
    - cron: '0 2 * * *'  # This means the workflow runs at 2 AM UTC daily
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update_ppt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run the update script
        run: |
          python update_ppt.py ${{ secrets.SOURCE_FILE_ID }} ${{ secrets.DESTINATION_FILE_ID }}
