name: Daily Update

on:
  schedule:
    - cron: '* * * * *'  # This runs every minute for testing
  workflow_dispatch:

jobs:
  update_files:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Update Script
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          AUTHORITY: ${{ secrets.AUTHORITY }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          SCOPES: ${{ secrets.SCOPES }}
          SITE_ID: ${{ secrets.SITE_ID }}
        run: |
          python update_ppt.py 3ACD0680-3BC0-4D66-A492-AAAA1669846D 51F9826C-7B53-4A60-A2F7-D05AC47E1618
