name: Daily Update

on:
  schedule:
    - cron: '0 2 * * *'  # Runs at 2 AM every day

jobs:
  update_ppt:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Ensure this version is available

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run update script
      run: |
        python update_ppt.py 3ACD0680-3BC0-4D66-A492-AAAA1669846D 51F9826C-7B53-4A60-A2F7-D05AC47E1618
