name: Simple Scheduled Test

on:
  schedule:
    - cron: '* * * * *'  # This runs every minute for testing

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Run a one-liner script
        run: echo "Scheduled workflow is running"
